# Generated by Django 5.2.4 on 2025-07-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='content',
            field=models.TextField(blank=True, help_text='Content to display on this page', verbose_name='Page Content'),
        ),
    ]
